import { Inter } from "next/font/google";
import "./globals.css";

<script async defer src="https://static.cdn.prismic.io/prismic.js?new=true&repo=my-testinn-r"></script>


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
